"""
Report builder: combines summaries, citations, visuals, and code into PDF/PPT.
Uses ReportLab for PDF and python-pptx for PowerPoint.
"""
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch
from reportlab.lib import colors
from pptx import Presentation
from pptx.util import Pt


class ReportBuilder:
    """Generate PDF and PPTX reports from analysis results."""

    def build_pdf(self, title, summary, citations=None, code_snippets=None):
        """Generate a PDF report. Returns bytes."""
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], fontSize=18, spaceAfter=20)
        heading_style = ParagraphStyle("ReportHeading", parent=styles["Heading2"], fontSize=14, spaceAfter=10)
        body_style = styles["BodyText"]

        story = []

        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 0.2*inch))

        story.append(Paragraph("Summary", heading_style))
        for line in summary.split("\n"):
            line = line.strip()
            if line:
                # Escape XML special chars for ReportLab
                safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(safe, body_style))
        story.append(Spacer(1, 0.2*inch))

        if citations:
            story.append(Paragraph("Citations &amp; References", heading_style))
            for i, cit in enumerate(citations, 1):
                meta = cit.get("metadata") or {}
                trust = cit.get("trust_score", 0)
                text = f"{i}. {meta.get('title', cit.get('original_text', 'Unknown'))}"
                if meta.get("authors"):
                    text += f" — {', '.join(meta['authors'][:3])}"
                if meta.get("year"):
                    text += f" ({meta['year']})"
                text += f" [Trust: {trust}/100]"
                safe = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(safe, body_style))
            story.append(Spacer(1, 0.2*inch))

        if code_snippets:
            story.append(Paragraph("Generated Code", heading_style))
            code_style = ParagraphStyle("Code", parent=body_style,
                                        fontName="Courier", fontSize=8,
                                        backColor=colors.Color(0.95, 0.95, 0.95))
            for snippet in code_snippets:
                concept = snippet.get("concept", "").replace("&", "&amp;").replace("<", "&lt;")
                story.append(Paragraph(f"Concept: {concept}", body_style))
                code_text = snippet.get("code", "")
                safe_code = code_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                safe_code = safe_code.replace("\n", "<br/>").replace(" ", "&nbsp;")
                story.append(Paragraph(safe_code, code_style))
                story.append(Spacer(1, 0.1*inch))

        doc.build(story)
        buf.seek(0)
        return buf.getvalue()

    def build_pptx(self, title, summary, citations=None, code_snippets=None):
        """Generate a PPTX report. Returns bytes."""
        prs = Presentation()

        # Title slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by Smart Research Assistant"

        # Summary slide
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Summary"
        body = slide.placeholders[1]
        tf = body.text_frame
        tf.text = ""
        for line in summary.split("\n")[:10]:
            line = line.strip()
            if line:
                p = tf.add_paragraph()
                p.text = line
                p.font.size = Pt(14)

        # Citations slide
        if citations:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = "Citations & Trust Scores"
            body = slide.placeholders[1]
            tf = body.text_frame
            tf.text = ""
            for cit in citations[:8]:
                meta = cit.get("metadata") or {}
                trust = cit.get("trust_score", 0)
                p = tf.add_paragraph()
                p.text = f"{meta.get('title', 'Unknown')} — Trust: {trust}/100"
                p.font.size = Pt(12)

        # Code slide
        if code_snippets:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = "Generated Code"
            body = slide.placeholders[1]
            tf = body.text_frame
            tf.text = ""
            for snippet in code_snippets[:3]:
                p = tf.add_paragraph()
                p.text = f"# {snippet.get('concept', '')}"
                p.font.size = Pt(11)
                p = tf.add_paragraph()
                p.text = snippet.get("code", "")[:300]
                p.font.size = Pt(10)

        buf = io.BytesIO()
        prs.save(buf)
        buf.seek(0)
        return buf.getvalue()
